[package]
name = "hk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate_type = ["cdylib"]

[dependencies]
itertools   = "0.10.1"
serde_json  = "1.0.1"
serde       = { version = "1.0.1", features = ["derive"]}

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
panic = "abort"

